[project]
name = "docker-exporter"
version = "0.1.0"
description = ""
authors = [
    {name = "vince-m4",email = "zjxuyunshi@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "docker (>=7.1.0,<8.0.0)"
]

[tool.poetry]
package-mode = false
packages = [{include = "docker_exporter", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
